name: "azblob-generate-static-index"
description: "Generate index.html for static web hosting on Azure Blob storage"
author: "fixpoint"
branding:
  icon: "list"
  color: "gray-dark"
inputs:
  connection-string:
    description: "Connection string"
    required: true
  container:
    description: "Container name"
    required: false
    default: "$web"
  prefix:
    description: "Prefix for index.html"
    required: true
  overwrite:
    description: "Allow to overwrite index.html (true/false)"
    required: true
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.connection-string }}
    - ${{ inputs.container }}
    - ${{ inputs.prefix }}
    - ${{ inputs.overwrite }}
